# Generated typing stub for protobuf runtime module.
from typing import Any
from google.protobuf.message import Message

class BBox(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    left: int
    top: int
    right: int
    bottom: int

class TrackKey(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    camera_id: str
    stream_epoch: str
    track_id: str

class RawI420Evidence(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    evidence_id: str
    data: bytes
    shape: list[int]
    dtype: str
    layout: str
    byte_length: int
    expiry_unix_ms: int

class EvidenceCaptureRequest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    trace_id: str
    evidence_id: str
    run_id: str

class Observation(Message):
    observed_in_frame: bool
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Observe(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class EndTrack(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class Cancel(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ClientEnvelope(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class JobReceipt(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class RecognitionUpdate(Message):
    raw_value: str
    aggregate_value: str
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class RecognitionOutcome(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class RecognitionArtifact(Message):
    frame_time: float
    track_id: str
    image_index: int
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ServiceHello(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ServerEnvelope(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ConfigureRequest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ConfigureResponse(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class CapabilitiesRequest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class CapabilitiesResponse(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class FaceLibraryRequest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class FaceLibraryResponse(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

RECOGNITION_TASK_FACE: int
RECOGNITION_TASK_LPR: int
RECOGNITION_OUTCOME_STATUS_SUCCEEDED: int
RECOGNITION_OUTCOME_STATUS_ENDED: int
RECOGNITION_OUTCOME_STATUS_CANCELLED: int
RECOGNITION_OUTCOME_STATUS_DEADLINE_EXCEEDED: int
RECOGNITION_OUTCOME_STATUS_FAILED: int
FACE_LIBRARY_OPERATION_REGISTER: int
FACE_LIBRARY_OPERATION_CLEAR: int
FACE_LIBRARY_OPERATION_RECOGNIZE: int
FACE_LIBRARY_OPERATION_REPROCESS: int
