# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import grpc.experimental

from . import tracker_pb2 as tracker__pb2


class TrackerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/camera.tracker.v1.TrackerService/Connect',
                request_serializer=tracker__pb2.MainEnvelope.SerializeToString,
                response_deserializer=tracker__pb2.EdgeEnvelope.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/camera.tracker.v1.TrackerService/Configure',
                request_serializer=tracker__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=tracker__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/camera.tracker.v1.TrackerService/GetCapabilities',
                request_serializer=tracker__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=tracker__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetEvidence = channel.unary_unary(
                '/camera.tracker.v1.TrackerService/GetEvidence',
                request_serializer=tracker__pb2.EvidenceRequest.SerializeToString,
                response_deserializer=tracker__pb2.EvidenceResponse.FromString,
                _registered_method=True)
        self.StreamMedia = channel.unary_stream(
                '/camera.tracker.v1.TrackerService/StreamMedia',
                request_serializer=tracker__pb2.MediaRequest.SerializeToString,
                response_deserializer=tracker__pb2.MediaChunk.FromString,
                _registered_method=True)
        self.ControlCamera = channel.unary_unary(
                '/camera.tracker.v1.TrackerService/ControlCamera',
                request_serializer=tracker__pb2.ControlRequest.SerializeToString,
                response_deserializer=tracker__pb2.ControlResponse.FromString,
                _registered_method=True)


class TrackerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMedia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=tracker__pb2.MainEnvelope.FromString,
                    response_serializer=tracker__pb2.EdgeEnvelope.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=tracker__pb2.ConfigureRequest.FromString,
                    response_serializer=tracker__pb2.ConfigureResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=tracker__pb2.CapabilitiesRequest.FromString,
                    response_serializer=tracker__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'GetEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvidence,
                    request_deserializer=tracker__pb2.EvidenceRequest.FromString,
                    response_serializer=tracker__pb2.EvidenceResponse.SerializeToString,
            ),
            'StreamMedia': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMedia,
                    request_deserializer=tracker__pb2.MediaRequest.FromString,
                    response_serializer=tracker__pb2.MediaChunk.SerializeToString,
            ),
            'ControlCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlCamera,
                    request_deserializer=tracker__pb2.ControlRequest.FromString,
                    response_serializer=tracker__pb2.ControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'camera.tracker.v1.TrackerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('camera.tracker.v1.TrackerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/camera.tracker.v1.TrackerService/Connect',
            tracker__pb2.MainEnvelope.SerializeToString,
            tracker__pb2.EdgeEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.tracker.v1.TrackerService/Configure',
            tracker__pb2.ConfigureRequest.SerializeToString,
            tracker__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.tracker.v1.TrackerService/GetCapabilities',
            tracker__pb2.CapabilitiesRequest.SerializeToString,
            tracker__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.tracker.v1.TrackerService/GetEvidence',
            tracker__pb2.EvidenceRequest.SerializeToString,
            tracker__pb2.EvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/camera.tracker.v1.TrackerService/StreamMedia',
            tracker__pb2.MediaRequest.SerializeToString,
            tracker__pb2.MediaChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.tracker.v1.TrackerService/ControlCamera',
            tracker__pb2.ControlRequest.SerializeToString,
            tracker__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
