# Generated typing stub for protobuf runtime module.
from typing import Any
from google.protobuf.message import Message

class BBox(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

CONTROL_OPERATION_CALIBRATE: int
CONTROL_OPERATION_DISABLE: int
CONTROL_OPERATION_ENABLE: int
CONTROL_OPERATION_MANUAL_PTZ: int
CONTROL_OPERATION_MEDIA_DELETE: int
CONTROL_OPERATION_MEDIA_RETAIN: int
CONTROL_OPERATION_PRESET: int
CONTROL_OPERATION_TOPOLOGY_DRAIN: int
CONTROL_OPERATION_UNSPECIFIED: int
class CameraHealth(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class CapabilitiesRequest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class CapabilitiesResponse(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ClientHello(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ConfigureRequest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ConfigureResponse(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ControlRequest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ControlResponse(Message):
    config_patch_json: str
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class EdgeEnvelope(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class EdgeHello(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class EvidenceReference(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class EvidenceRequest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class EvidenceResponse(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class HealthRequest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class JournalAck(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class LifecycleFailure(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MainEnvelope(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MediaChunk(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MediaManifest(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class MediaRequest(Message):
    length: int
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class NodeHealth(Message):
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

TRACKER_OPERATION_END: int
TRACKER_OPERATION_START: int
TRACKER_OPERATION_UNSPECIFIED: int
TRACKER_OPERATION_UPDATE: int
class TrackerUpdate(Message):
    speed: float
    def __init__(self, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

