# ruff: noqa
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from frigate.recognition.service.v1 import recognition_pb2 as frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in frigate/recognition/service/v1/recognition_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecognitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.stream_stream(
                '/camera.recognition.v1.RecognitionService/Recognize',
                request_serializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ClientEnvelope.SerializeToString,
                response_deserializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ServerEnvelope.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/camera.recognition.v1.RecognitionService/Configure',
                request_serializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/camera.recognition.v1.RecognitionService/GetCapabilities',
                request_serializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.ManageFaceLibrary = channel.unary_unary(
                '/camera.recognition.v1.RecognitionService/ManageFaceLibrary',
                request_serializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.FaceLibraryRequest.SerializeToString,
                response_deserializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.FaceLibraryResponse.FromString,
                _registered_method=True)


class RecognitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Recognize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManageFaceLibrary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.stream_stream_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ClientEnvelope.FromString,
                    response_serializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ServerEnvelope.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ConfigureRequest.FromString,
                    response_serializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ConfigureResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.CapabilitiesRequest.FromString,
                    response_serializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'ManageFaceLibrary': grpc.unary_unary_rpc_method_handler(
                    servicer.ManageFaceLibrary,
                    request_deserializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.FaceLibraryRequest.FromString,
                    response_serializer=frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.FaceLibraryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'camera.recognition.v1.RecognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('camera.recognition.v1.RecognitionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecognitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Recognize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/camera.recognition.v1.RecognitionService/Recognize',
            frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ClientEnvelope.SerializeToString,
            frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ServerEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.recognition.v1.RecognitionService/Configure',
            frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ConfigureRequest.SerializeToString,
            frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.recognition.v1.RecognitionService/GetCapabilities',
            frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.CapabilitiesRequest.SerializeToString,
            frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManageFaceLibrary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/camera.recognition.v1.RecognitionService/ManageFaceLibrary',
            frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.FaceLibraryRequest.SerializeToString,
            frigate_dot_recognition_dot_service_dot_v1_dot_recognition__pb2.FaceLibraryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
